<?php

namespace Citagora\Entity\Document;
use Citagora\EntityManager\Entity;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\EmbeddedDocument
 */
class Meta extends Entity
{
    /**
     * @var int
     * @ODM\Id     
     */
    protected $identifier;

    /**
     * @var array
     * @ODM\Collection
     */
    protected $sources;

    /**
     * @var int  Generated by
     * Either a user ID or '0' for harvester
     */
    protected $generatedBy;

    /**
     * @var DateTime
     * Date record was added in system
     */
    protected $created;

    /**
     * @var DateTime
     * Date record last modified
     */
    protected $modified;

    // --------------------------------------------------------------

    /**
     * Do stuff before saving
     *
     * @ODM\PrePersist 
     */
    public function prePersist()
    {
        //Created
        if ( ! $this->created) {
            $this->created = time();
        }

        //Modified
        $this->modified = time();
    }    
}

/* EOF: Meta.php */