#!/usr/bin/env php
<?php

/**
 * Console Interface for Citagora
 *
 * @package Citagora
 * @author Casey McLaughlin
 */

//Autoloader
require __DIR__ . '/../vendor/autoload.php';

//Run it! Let's Go!
\Citagora\Cli\App::main();

/* EOF: import */