<?php

namespace Citagora\Common\Entity\Document;

use Citagora\Common\EntityManager\Entity;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\EmbeddedDocument
 */
class Meta extends Entity
{
    /**
     * @var array  Key is DataSource slug, value is identifier at that datasource
     * @ODM\Hash  
     */
    protected $sources;

    /**
     * @var string  Generated by (Either a user ID or '0' for harvester)
     * @ODM\string
     */
    protected $generatedBy;

    /**
     * @var DateTime Date record was added in system
     * @ODM\Timestamp
     */
    protected $created;

    /**
     * @var DateTime Date record last modified
     * @ODM\Timestamp
     */
    protected $modified;

    // --------------------------------------------------------------

    public function __construct()
    {
        $this->sources = array();
    }

    // --------------------------------------------------------------

    public function __set($item, $value)
    {
        switch ($item) {
            case 'sources':
            case 'created':
            case 'modified':
                throw new \Exception("Cannot modify {$item} directly");
        }

        return parent::__set($item, $value);
    }

    // --------------------------------------------------------------

    /**
     * Add a source for this record
     *
     * @param string $sourceName
     * @param string $sourceIdentifier
     */
    public function addSource($sourceName, $sourceIdentifier)
    {
        if ( ! in_array($sourceName, $this->sources)) {
            $this->sources[$sourceName] = $sourceIdentifier;
        }
    }

    // --------------------------------------------------------------

    /**
     * Do stuff before saving
     *
     * @ODM\PrePersist 
     */
    public function prePersist()
    {
        //Created
        if ( ! $this->created) {
            $this->created = time();
        }

        //Modified
        $this->modified = time();
    }    
}

/* EOF: Meta.php */